[workspace]
members = [
    "./gband",
    "./gband-wgpu",
    "./gband-server",
    "./gband-webclient",
]
resolver = "2"

[profile.dev]
# Slightly better optimizations.
opt-level = 1

[profile.release]
codegen-units = 1
